### ISSUE TITLE
Надо переписать все эти конструкции на try + ресурсы и убрать везде null

### ISSUE THREAD

**Issue by coursar** [s585/layers#10]
https://github.com/s585/layers/blob/da4e27f0be5424ea790ecb0445ce4537924ae353/src/main/java/tech/itpark/repository/UserRepositoryJDBCImpl.java#L139-L146

**Comment by s585** [comment]
Убрал в try() все ResultSet'ы. Не знаю, как инициализировать переменные без null'ов.
Посмотрите, пожалуйста, метод save. Как правильно отправить значение поле типа Set в поле таблицы типа TEXT[]?  
Выполнение приводит к ошибке:

Exception in thread "main" tech.itpark.exception.DataAccessException: org.postgresql.util.PSQLException: Cannot cast an instance of [Ljava.lang.Object; to type Types.ARRAY
	at tech.itpark.repository.UserRepositoryJDBCImpl.save(UserRepositoryJDBCImpl.java:106)
	at tech.itpark.repository.UserRepositoryJDBCImpl.save(UserRepositoryJDBCImpl.java:13)
	at tech.itpark.Main.main(Main.java:29)
Caused by: org.postgresql.util.PSQLException: Cannot cast an instance of [Ljava.lang.Object; to type Types.ARRAY
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:693)
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:935)
	at tech.itpark.repository.UserRepositoryJDBCImpl.save(UserRepositoryJDBCImpl.java:98)
	... 2 more

**Comment by coursar** [comment]
Пример же в лекциях есть (в презентации).
